import type { Metadata } from "next";
import { Inter, Instrument_Serif } from "next/font/google";
import "./globals.css";
import Wave from "@/components/wave";
import { cn } from "@/lib/utils";
import { SensoryUIProvider } from "@/components/ui/sensory-ui/config/provider";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        inter.variable,
        instrumentSerif.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col">
        <div>
          <Wave />
        </div>
        <div className="absolute inset-x-0 h-[39vh] bg-gradient-to-t from-background via-background/80 to-background/30 pointer-events-none z-10" />
        <SensoryUIProvider config={{ theme: "retro", volume: 0.5 }}>
          {children}
        </SensoryUIProvider>
      </body>
    </html>
  );
}
